//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceModel.Cancellation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceModel.Cancellation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is already started..
        /// </summary>
        internal static string BeginOperationTwoTimes {
            get {
                return ResourceManager.GetString("BeginOperationTwoTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is alredy canceled..
        /// </summary>
        internal static string CancelOperationTwoTimes {
            get {
                return ResourceManager.GetString("CancelOperationTwoTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to parse CancellationBehaviorElement/clientOptions[@contractFactory] value [{0}]..
        /// </summary>
        internal static string ClientCancellationOptionsElementContractFactory0 {
            get {
                return ResourceManager.GetString("ClientCancellationOptionsElementContractFactory0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [public static ICancellationContract {0}()] not found in [{1}]..
        /// </summary>
        internal static string ClientCancellationOptionsElementMethodNotFound1 {
            get {
                return ResourceManager.GetString("ClientCancellationOptionsElementMethodNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [public static ICancellationContract {1}()] found in [{2}]..
        /// </summary>
        internal static string ClientCancellationOptionsElementTooManyMethodsFound2 {
            get {
                return ResourceManager.GetString("ClientCancellationOptionsElementTooManyMethodsFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is already completed..
        /// </summary>
        internal static string EndOperationTwoTimes {
            get {
                return ResourceManager.GetString("EndOperationTwoTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to resolve service {0}..
        /// </summary>
        internal static string FailToResolveService0 {
            get {
                return ResourceManager.GetString("FailToResolveService0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0}, {1} is not supported as return/out/ref arguments..
        /// </summary>
        internal static string OperationIsNotSupportedAsReturnArguments1 {
            get {
                return ResourceManager.GetString("OperationIsNotSupportedAsReturnArguments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0}, {1} is not supported in this context..
        /// </summary>
        internal static string OperationIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("OperationIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0}, there are {1} {2} detected..
        /// </summary>
        internal static string OperationThereAreDetected2 {
            get {
                return ResourceManager.GetString("OperationThereAreDetected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] cannot be interpreted as [ClassName.MethodName, AssemblyName]..
        /// </summary>
        internal static string ParseFullMethodNameInvalidInput0 {
            get {
                return ResourceManager.GetString("ParseFullMethodNameInvalidInput0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider {0} does not support service {1}..
        /// </summary>
        internal static string ProviderDoesNotSupportService1 {
            get {
                return ResourceManager.GetString("ProviderDoesNotSupportService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service endpoint host is already configured to use cancellation..
        /// </summary>
        internal static string ServiceEndpointUseCancellationTwice {
            get {
                return ResourceManager.GetString("ServiceEndpointUseCancellationTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host is already configured to use cancellation..
        /// </summary>
        internal static string ServiceHostUseCancellationTwice {
            get {
                return ResourceManager.GetString("ServiceHostUseCancellationTwice", resourceCulture);
            }
        }
    }
}
